# Usar una imagen base oficial de Python
FROM python:3.10-slim

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar el archivo requirements.txt al contenedor
COPY requirements.txt .

# Instalar las dependencias necesarias
RUN pip install --no-cache-dir -r requirements.txt

# Copiar el resto del código de la aplicación al contenedor
COPY . .

# Exponer el puerto en el que corre la aplicación (si aplica)
# EXPOSE 8000

# Comando para ejecutar la aplicación
CMD ["python", "main.py"]


# Abre una terminal y navega hasta el directorio del proyecto.
# Construye la imagen de Docker:
#   docker build -t image_name .
# Ejecuta un contenedor usando la imagen que acabas de construir:
#   docker run -d --name container_name image_name
